//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsanPardakht.Verify {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfApiSpecialVerifyResponseXceKj1Fg", Namespace="http://schemas.datacontract.org/2004/07/Ipg.Engine.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseOfApiSpecialVerifyResponseXceKj1Fg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AsanPardakht.Verify.ApiSpecialVerifyResponse resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.respCodeField, value) != true)) {
                    this.respCodeField = value;
                    this.RaisePropertyChanged("respCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AsanPardakht.Verify.ApiSpecialVerifyResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiSpecialVerifyResponse", Namespace="http://schemas.datacontract.org/2004/07/Ipg.Engine.Model")]
    [System.SerializableAttribute()]
    public partial class ApiSpecialVerifyResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfApiRevereseResponseXceKj1Fg", Namespace="http://schemas.datacontract.org/2004/07/Ipg.Engine.Model")]
    [System.SerializableAttribute()]
    public partial class ResponseOfApiRevereseResponseXceKj1Fg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string respCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AsanPardakht.Verify.ApiRevereseResponse resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string respCode {
            get {
                return this.respCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.respCodeField, value) != true)) {
                    this.respCodeField = value;
                    this.RaisePropertyChanged("respCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AsanPardakht.Verify.ApiRevereseResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApiRevereseResponse", Namespace="http://schemas.datacontract.org/2004/07/Ipg.Engine.Model")]
    [System.SerializableAttribute()]
    public partial class ApiRevereseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="transactionModel", Namespace="http://schemas.datacontract.org/2004/07/VerifyPayment")]
    [System.SerializableAttribute()]
    public partial class transactionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AMOUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CARDNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXTRAPARAM1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXTRAPARAM2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXTRAPARAM3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EXTRAPARAM4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MERCHANTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAYMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REFERENCENUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESULTCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROWNUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SETTLEMENTDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPECIALPAYMENTIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRANSDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VERIFYDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VERIFYRESPONSEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AMOUNT {
            get {
                return this.AMOUNTField;
            }
            set {
                if ((object.ReferenceEquals(this.AMOUNTField, value) != true)) {
                    this.AMOUNTField = value;
                    this.RaisePropertyChanged("AMOUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CARDNO {
            get {
                return this.CARDNOField;
            }
            set {
                if ((object.ReferenceEquals(this.CARDNOField, value) != true)) {
                    this.CARDNOField = value;
                    this.RaisePropertyChanged("CARDNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM1 {
            get {
                return this.EXTRAPARAM1Field;
            }
            set {
                if ((object.ReferenceEquals(this.EXTRAPARAM1Field, value) != true)) {
                    this.EXTRAPARAM1Field = value;
                    this.RaisePropertyChanged("EXTRAPARAM1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM2 {
            get {
                return this.EXTRAPARAM2Field;
            }
            set {
                if ((object.ReferenceEquals(this.EXTRAPARAM2Field, value) != true)) {
                    this.EXTRAPARAM2Field = value;
                    this.RaisePropertyChanged("EXTRAPARAM2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM3 {
            get {
                return this.EXTRAPARAM3Field;
            }
            set {
                if ((object.ReferenceEquals(this.EXTRAPARAM3Field, value) != true)) {
                    this.EXTRAPARAM3Field = value;
                    this.RaisePropertyChanged("EXTRAPARAM3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EXTRAPARAM4 {
            get {
                return this.EXTRAPARAM4Field;
            }
            set {
                if ((object.ReferenceEquals(this.EXTRAPARAM4Field, value) != true)) {
                    this.EXTRAPARAM4Field = value;
                    this.RaisePropertyChanged("EXTRAPARAM4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MERCHANTID {
            get {
                return this.MERCHANTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.MERCHANTIDField, value) != true)) {
                    this.MERCHANTIDField = value;
                    this.RaisePropertyChanged("MERCHANTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAYMENTID {
            get {
                return this.PAYMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PAYMENTIDField, value) != true)) {
                    this.PAYMENTIDField = value;
                    this.RaisePropertyChanged("PAYMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REFERENCENUMBER {
            get {
                return this.REFERENCENUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.REFERENCENUMBERField, value) != true)) {
                    this.REFERENCENUMBERField = value;
                    this.RaisePropertyChanged("REFERENCENUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESULTCODE {
            get {
                return this.RESULTCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.RESULTCODEField, value) != true)) {
                    this.RESULTCODEField = value;
                    this.RaisePropertyChanged("RESULTCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROWNUMBER {
            get {
                return this.ROWNUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.ROWNUMBERField, value) != true)) {
                    this.ROWNUMBERField = value;
                    this.RaisePropertyChanged("ROWNUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SETTLEMENTDATE {
            get {
                return this.SETTLEMENTDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.SETTLEMENTDATEField, value) != true)) {
                    this.SETTLEMENTDATEField = value;
                    this.RaisePropertyChanged("SETTLEMENTDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPECIALPAYMENTID {
            get {
                return this.SPECIALPAYMENTIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SPECIALPAYMENTIDField, value) != true)) {
                    this.SPECIALPAYMENTIDField = value;
                    this.RaisePropertyChanged("SPECIALPAYMENTID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRANSDATE {
            get {
                return this.TRANSDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.TRANSDATEField, value) != true)) {
                    this.TRANSDATEField = value;
                    this.RaisePropertyChanged("TRANSDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VERIFYDATE {
            get {
                return this.VERIFYDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.VERIFYDATEField, value) != true)) {
                    this.VERIFYDATEField = value;
                    this.RaisePropertyChanged("VERIFYDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VERIFYRESPONSE {
            get {
                return this.VERIFYRESPONSEField;
            }
            set {
                if ((object.ReferenceEquals(this.VERIFYRESPONSEField, value) != true)) {
                    this.VERIFYRESPONSEField = value;
                    this.RaisePropertyChanged("VERIFYRESPONSE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoceNo {
            get {
                return this.invoceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.invoceNoField, value) != true)) {
                    this.invoceNoField = value;
                    this.RaisePropertyChanged("invoceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardModel", Namespace="http://schemas.datacontract.org/2004/07/VerifyPayment")]
    [System.SerializableAttribute()]
    public partial class CardModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HCode {
            get {
                return this.HCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HCodeField, value) != true)) {
                    this.HCodeField = value;
                    this.RaisePropertyChanged("HCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Verify.IVerify")]
    public interface IVerify {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccPaymentsVerification", ReplyAction="http://tempuri.org/IVerify/KicccPaymentsVerificationResponse")]
        long KicccPaymentsVerification(string token, string merchantId, string referenceNumber, string sha1Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccPaymentsVerification", ReplyAction="http://tempuri.org/IVerify/KicccPaymentsVerificationResponse")]
        System.Threading.Tasks.Task<long> KicccPaymentsVerificationAsync(string token, string merchantId, string referenceNumber, string sha1Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccSpecialVerification", ReplyAction="http://tempuri.org/IVerify/KicccSpecialVerificationResponse")]
        AsanPardakht.Verify.ResponseOfApiSpecialVerifyResponseXceKj1Fg KicccSpecialVerification(string token, string merchantId, string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccSpecialVerification", ReplyAction="http://tempuri.org/IVerify/KicccSpecialVerificationResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.ResponseOfApiSpecialVerifyResponseXceKj1Fg> KicccSpecialVerificationAsync(string token, string merchantId, string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccReverse", ReplyAction="http://tempuri.org/IVerify/KicccReverseResponse")]
        AsanPardakht.Verify.ResponseOfApiRevereseResponseXceKj1Fg KicccReverse(string token, string merchantId, string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/KicccReverse", ReplyAction="http://tempuri.org/IVerify/KicccReverseResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.ResponseOfApiRevereseResponseXceKj1Fg> KicccReverseAsync(string token, string merchantId, string referenceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getTransaction", ReplyAction="http://tempuri.org/IVerify/getTransactionResponse")]
        AsanPardakht.Verify.transactionModel getTransaction(string merchantId, string invoiceNo, string referenceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getTransaction", ReplyAction="http://tempuri.org/IVerify/getTransactionResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel> getTransactionAsync(string merchantId, string invoiceNo, string referenceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getLimitedTransacction", ReplyAction="http://tempuri.org/IVerify/getLimitedTransacctionResponse")]
        AsanPardakht.Verify.transactionModel getLimitedTransacction(string merchantId, string invoiceNo, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getLimitedTransacction", ReplyAction="http://tempuri.org/IVerify/getLimitedTransacctionResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel> getLimitedTransacctionAsync(string merchantId, string invoiceNo, string amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getDailyTransaction", ReplyAction="http://tempuri.org/IVerify/getDailyTransactionResponse")]
        AsanPardakht.Verify.transactionModel[] getDailyTransaction(string merchantId, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getDailyTransaction", ReplyAction="http://tempuri.org/IVerify/getDailyTransactionResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getDailyTransactionAsync(string merchantId, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getOfflineTransaction", ReplyAction="http://tempuri.org/IVerify/getOfflineTransactionResponse")]
        AsanPardakht.Verify.transactionModel[] getOfflineTransaction(string merchantId, string fromDate, string toDate, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getOfflineTransaction", ReplyAction="http://tempuri.org/IVerify/getOfflineTransactionResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getOfflineTransactionAsync(string merchantId, string fromDate, string toDate, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getTransactionByIban", ReplyAction="http://tempuri.org/IVerify/getTransactionByIbanResponse")]
        AsanPardakht.Verify.transactionModel[] getTransactionByIban(string merchantId, string IbanNo, string fromDate, string toDate, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/getTransactionByIban", ReplyAction="http://tempuri.org/IVerify/getTransactionByIbanResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getTransactionByIbanAsync(string merchantId, string IbanNo, string fromDate, string toDate, string offset, string limit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/GetCardsPerKey", ReplyAction="http://tempuri.org/IVerify/GetCardsPerKeyResponse")]
        AsanPardakht.Verify.CardModel[] GetCardsPerKey(string merchantId, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerify/GetCardsPerKey", ReplyAction="http://tempuri.org/IVerify/GetCardsPerKeyResponse")]
        System.Threading.Tasks.Task<AsanPardakht.Verify.CardModel[]> GetCardsPerKeyAsync(string merchantId, string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVerifyChannel : AsanPardakht.Verify.IVerify, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerifyClient : System.ServiceModel.ClientBase<AsanPardakht.Verify.IVerify>, AsanPardakht.Verify.IVerify {
        
        public VerifyClient() {
        }
        
        public VerifyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerifyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerifyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long KicccPaymentsVerification(string token, string merchantId, string referenceNumber, string sha1Key) {
            return base.Channel.KicccPaymentsVerification(token, merchantId, referenceNumber, sha1Key);
        }
        
        public System.Threading.Tasks.Task<long> KicccPaymentsVerificationAsync(string token, string merchantId, string referenceNumber, string sha1Key) {
            return base.Channel.KicccPaymentsVerificationAsync(token, merchantId, referenceNumber, sha1Key);
        }
        
        public AsanPardakht.Verify.ResponseOfApiSpecialVerifyResponseXceKj1Fg KicccSpecialVerification(string token, string merchantId, string referenceNumber) {
            return base.Channel.KicccSpecialVerification(token, merchantId, referenceNumber);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.ResponseOfApiSpecialVerifyResponseXceKj1Fg> KicccSpecialVerificationAsync(string token, string merchantId, string referenceNumber) {
            return base.Channel.KicccSpecialVerificationAsync(token, merchantId, referenceNumber);
        }
        
        public AsanPardakht.Verify.ResponseOfApiRevereseResponseXceKj1Fg KicccReverse(string token, string merchantId, string referenceNumber) {
            return base.Channel.KicccReverse(token, merchantId, referenceNumber);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.ResponseOfApiRevereseResponseXceKj1Fg> KicccReverseAsync(string token, string merchantId, string referenceNumber) {
            return base.Channel.KicccReverseAsync(token, merchantId, referenceNumber);
        }
        
        public AsanPardakht.Verify.transactionModel getTransaction(string merchantId, string invoiceNo, string referenceNo) {
            return base.Channel.getTransaction(merchantId, invoiceNo, referenceNo);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel> getTransactionAsync(string merchantId, string invoiceNo, string referenceNo) {
            return base.Channel.getTransactionAsync(merchantId, invoiceNo, referenceNo);
        }
        
        public AsanPardakht.Verify.transactionModel getLimitedTransacction(string merchantId, string invoiceNo, string amount) {
            return base.Channel.getLimitedTransacction(merchantId, invoiceNo, amount);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel> getLimitedTransacctionAsync(string merchantId, string invoiceNo, string amount) {
            return base.Channel.getLimitedTransacctionAsync(merchantId, invoiceNo, amount);
        }
        
        public AsanPardakht.Verify.transactionModel[] getDailyTransaction(string merchantId, string offset, string limit) {
            return base.Channel.getDailyTransaction(merchantId, offset, limit);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getDailyTransactionAsync(string merchantId, string offset, string limit) {
            return base.Channel.getDailyTransactionAsync(merchantId, offset, limit);
        }
        
        public AsanPardakht.Verify.transactionModel[] getOfflineTransaction(string merchantId, string fromDate, string toDate, string offset, string limit) {
            return base.Channel.getOfflineTransaction(merchantId, fromDate, toDate, offset, limit);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getOfflineTransactionAsync(string merchantId, string fromDate, string toDate, string offset, string limit) {
            return base.Channel.getOfflineTransactionAsync(merchantId, fromDate, toDate, offset, limit);
        }
        
        public AsanPardakht.Verify.transactionModel[] getTransactionByIban(string merchantId, string IbanNo, string fromDate, string toDate, string offset, string limit) {
            return base.Channel.getTransactionByIban(merchantId, IbanNo, fromDate, toDate, offset, limit);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.transactionModel[]> getTransactionByIbanAsync(string merchantId, string IbanNo, string fromDate, string toDate, string offset, string limit) {
            return base.Channel.getTransactionByIbanAsync(merchantId, IbanNo, fromDate, toDate, offset, limit);
        }
        
        public AsanPardakht.Verify.CardModel[] GetCardsPerKey(string merchantId, string key) {
            return base.Channel.GetCardsPerKey(merchantId, key);
        }
        
        public System.Threading.Tasks.Task<AsanPardakht.Verify.CardModel[]> GetCardsPerKeyAsync(string merchantId, string key) {
            return base.Channel.GetCardsPerKeyAsync(merchantId, key);
        }
    }
}
